services:
  misbalanzasv1-web:
    container_name: misbalanzasv1-web
    image: santiagofragio/nginx:latest
    ports:
      - 300:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - misbalanzasv1-network
    depends_on:
      - misbalanzasv1-be

  misbalanzasv1-be:
    container_name: misbalanzasv1-be
    image: santiagofragio/php:latest
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
#      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9005 # MacOS users
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini # Linux users
#    - ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini # MacOS users
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    networks:
      - misbalanzasv1-network
    depends_on:
      - misbalanzasv1-db

  misbalanzasv1-db:
    container_name: misbalanzasv1-db
    image: mysql:8.0
    ports:
      - 40000:3306
    environment:
      MYSQL_DATABASE: misbalanzasv1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - misbalanzasv1-database-data:/var/lib/mysql
    networks:
      - misbalanzasv1-network

volumes:
  misbalanzasv1-database-data:

networks:
  misbalanzasv1-network:
    external: true
